#!/bin/bash

echo "=== Testing Enhanced MKV Extraction ==="
echo "The AudioIO class now supports multiple extraction methods for mkv files:"
echo ""
echo "1. Standard MediaExtractor.setDataSource()"
echo "2. Alternative with HTTP headers (User-Agent: Mozilla/5.0)"
echo "3. Alternative with direct file path instead of URI"
echo "4. Graceful fallback with empty PCM (no crash)"
echo ""
echo "Key improvements:"
echo "✅ Try-catch blocks around MediaExtractor calls"
echo "✅ Multiple fallback extraction methods"
echo "✅ Detailed logging to track which method works"
echo "✅ Graceful degradation instead of crashes"
echo "✅ Support for problematic mkv codecs/containers"
echo ""
echo "The extractor should now handle TennisInterview.mkv and other"
echo "problematic mkv files that previously caused 'Failed to instantiate extractor' errors."
echo ""
echo "To test: Select TennisInterview.mkv from Documents folder in the app"
echo "The logs will show which extraction method succeeds."
