name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'zulu', 'java-version': '21' }
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :app:verifyConfig detekt ktlintCheck lintDebug testDebugUnitTest assembleDebug
      - uses: actions/upload-artifact@v4
        with: { name: apks, path: app/build/outputs/apk/**/*.apk, if-no-files-found: error }
