name: Artifact Cleanup

on:
  schedule:
    # Run every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  cleanup-artifacts:
    name: Cleanup Old Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cleanup old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 30); // Keep artifacts for 30 days
            
            let deletedCount = 0;
            let keptCount = 0;
            
            for (const artifact of artifacts.artifacts) {
              const artifactDate = new Date(artifact.created_at);
              
              if (artifactDate < cutoffDate) {
                try {
                  await github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: artifact.id
                  });
                  console.log(`Deleted artifact: ${artifact.name} (${artifact.created_at})`);
                  deletedCount++;
                } catch (error) {
                  console.log(`Failed to delete artifact: ${artifact.name} - ${error.message}`);
                }
              } else {
                console.log(`Kept artifact: ${artifact.name} (${artifact.created_at})`);
                keptCount++;
              }
            }
            
            console.log(`Cleanup completed: ${deletedCount} deleted, ${keptCount} kept`);
            
      - name: Generate cleanup report
        run: |
          echo "## Artifact Cleanup Report" >> $GITHUB_STEP_SUMMARY
          echo "- **Date**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Action**: Cleaned up artifacts older than 30 days" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: Completed successfully" >> $GITHUB_STEP_SUMMARY
