name: Policy Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [ main ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }   # need history to diff against origin/main
      - name: Setup Java
        uses: actions/setup-java@v4
        with: { distribution: 'zulu', java-version: '21' }
      - uses: gradle/actions/setup-gradle@v4
      - name: Make scripts executable
        run: chmod +x tools/push_guard.sh || true
      - name: Run policy guard
        run: tools/push_guard.sh --ci
      - name: Fast gradle checks
        run: ./gradlew :app:verifyConfig ktlintCheck detekt testDebugUnitTest -x lint
